#!/bin/bash

. ~/bin/colordefs.sh

names=('latest'
       '4.3')

bin_postfixes=(''
               '-4.3')

bin_dir='/usr/bin/'
basenames=('c++' 'cpp' 'g++' 'gcc' 'gcov')

gccvm_root="$HOME/.gccvm/"
gccvm_bin="${gccvm_root}bin/"

SCAN_DIRS=('/usr/bin' '/usr/local/bin' '/bin')
LS_FILE="${gccvm_root}/.gcc.list"

function err()
{
  ec $RED "$1"
  exit 2
}

function get_version()
{
  echo `$1 --version | head -n1 | cut -d' ' -f3`
}

function load()
{
  echo
}

function list()
{
  load
  echo "Possible versions:"
  for (( i = 0; i < ${#names[@]}; i++ ))
  do
    echo -ne "  "
    ec $YELLOW " ${names[$i]} ${GREEN} (`get_version ${bin_dir}g++${bin_postfixes[$i]}`)" 
  done
}

function usage()
{
  echo "Usage: gccvm <command>"
  echo "  Commands:"
  echo "    list          - lists possible gcc versions"
  echo "    select <name> - selects gcc version"
  echo "    scan          - scans some directory for gcc binaries (warning! Overwrites existing config!)"
  ec $YELLOW "Current gcc version:"
  g++ --version | head -n1
}

function index_of()
{
  count=${#names[@]}
  let count--
  for i in `seq 0 ${count}`
  do
    [ "${names[$i]}" == "$1" ] && index=$i
  done
}

function select_gcc()
{
  ec $YELLOW "Selecting '${RED}$1${YELLOW}' ..."
  index_of "$1"
  [[ "${index}" < "0" ]] && err "Name not exists: '$1'"

  ec $THIN_CYAN "Binaries to be linked:"
  for i in ${basenames[@]}
  do
    bin=${bin_dir}$i${bin_postfixes[$index]}
    echo -ne "  Checking $YELLOW$bin$NOCOLOR ... "
    if [ ! -f "$bin" ]; then
      err "Not exists: '$bin'!"
    else
      ec $GREEN "OK!"
    fi
  done

  for i in ${basenames[@]}
  do
    bin=${bin_dir}$i${bin_postfixes[$index]}
    echo -ne '  '
    ln -sfv ${bin} ${gccvm_bin}$i
  done
  ec $GREEN "Switched to '$1' SUCCESS!"
  ${gccvm_bin}g++ --version | head -n1
  g++ --version | head -n1
}

function scan()
{
  echo -ne > ${LS_FILE}

  ec $YELLOW "Searching for GCC binaries in ${GREEN} ${SCAN_DIRS[*]} ${YELLOW}..."
  for i in ${SCAN_DIRS[@]}
  do
    for j in `/bin/ls $i | egrep '^gcc(-[0-9\.]+)*$'`
    do
      bin="$i/$j"
      if [ -f "$bin" ]; then
        vers=`get_version $bin`
        echo -e "${RED}FOUND${NOCOLOR} gcc in: $i, version: ${YELLOW}`get_version $bin`$NOCOLOR"
        echo "$vers $bin" >> ${LS_FILE}
      fi
    done
  done
}

# current_version=

case "$1" in
  list)
    list
  ;;
  select)
    select_gcc $2
  ;;
  scan)
    scan
  ;;
  *)
  usage
esac




